name: EC2 auto deploy

# mainにpush時アクションが実行
on:
 push:
   branches:
     - main
 
#実行処理
jobs:
 build:
   # 実行環境
   runs-on: ubuntu-latest
   steps:

     # デプロイする
     - name: Deploy
       run: |
         # SSH接続して、git pullする
         echo "${{ secrets.PRIVATE_KEY }}" > private_key
         chmod 600 private_key
         ssh -oStrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} -i private_key "cd [リポジトリのディレクトリ] && git fetch github:shuncask/kanpai.git && git pull github:shuncask/kanpai.git"
         
